'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace SDiEmailUtilityService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="EmailServicesSoap", [Namespace]:="http://www.sdiexchange.com/")>  _
    Partial Public Class EmailServices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EmailUtilityServicesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EmailUtilityServicesSPCTOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ConsoleApp1.My.MySettings.Default.ConsoleApp1_sdixaws2016test_EmailServices
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EmailUtilityServicesCompleted As EmailUtilityServicesCompletedEventHandler
        
        '''<remarks/>
        Public Event EmailUtilityServicesSPCTCompleted As EmailUtilityServicesSPCTCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sdiexchange.com/EmailUtilityServices", RequestNamespace:="http://www.sdiexchange.com/", ResponseNamespace:="http://www.sdiexchange.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EmailUtilityServices(ByVal ProcessType As String, ByVal FromAddress As String, ByVal ToAddress As String, ByVal MailSubject As String, ByVal MailCC As String, ByVal MAILBCC As String, ByVal MailBody As String, ByVal MailCategory As String, ByVal AttachmentName() As String, ByVal Attachmentbytes()() As Byte) As String
            Dim results() As Object = Me.Invoke("EmailUtilityServices", New Object() {ProcessType, FromAddress, ToAddress, MailSubject, MailCC, MAILBCC, MailBody, MailCategory, AttachmentName, Attachmentbytes})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EmailUtilityServicesAsync(ByVal ProcessType As String, ByVal FromAddress As String, ByVal ToAddress As String, ByVal MailSubject As String, ByVal MailCC As String, ByVal MAILBCC As String, ByVal MailBody As String, ByVal MailCategory As String, ByVal AttachmentName() As String, ByVal Attachmentbytes()() As Byte)
            Me.EmailUtilityServicesAsync(ProcessType, FromAddress, ToAddress, MailSubject, MailCC, MAILBCC, MailBody, MailCategory, AttachmentName, Attachmentbytes, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EmailUtilityServicesAsync(ByVal ProcessType As String, ByVal FromAddress As String, ByVal ToAddress As String, ByVal MailSubject As String, ByVal MailCC As String, ByVal MAILBCC As String, ByVal MailBody As String, ByVal MailCategory As String, ByVal AttachmentName() As String, ByVal Attachmentbytes()() As Byte, ByVal userState As Object)
            If (Me.EmailUtilityServicesOperationCompleted Is Nothing) Then
                Me.EmailUtilityServicesOperationCompleted = AddressOf Me.OnEmailUtilityServicesOperationCompleted
            End If
            Me.InvokeAsync("EmailUtilityServices", New Object() {ProcessType, FromAddress, ToAddress, MailSubject, MailCC, MAILBCC, MailBody, MailCategory, AttachmentName, Attachmentbytes}, Me.EmailUtilityServicesOperationCompleted, userState)
        End Sub
        
        Private Sub OnEmailUtilityServicesOperationCompleted(ByVal arg As Object)
            If (Not (Me.EmailUtilityServicesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EmailUtilityServicesCompleted(Me, New EmailUtilityServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sdiexchange.com/EmailUtilityServicesSPCT", RequestNamespace:="http://www.sdiexchange.com/", ResponseNamespace:="http://www.sdiexchange.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EmailUtilityServicesSPCT(ByVal ProcessType As String, ByVal FromAddress As String, ByVal ToAddress As String, ByVal MailSubject As String, ByVal MailCC As String, ByVal MAILBCC As String, ByVal MailBody As String, ByVal MailCategory As String, ByVal AttachmentName() As String, ByVal Attachmentbytes()() As Byte) As String
            Dim results() As Object = Me.Invoke("EmailUtilityServicesSPCT", New Object() {ProcessType, FromAddress, ToAddress, MailSubject, MailCC, MAILBCC, MailBody, MailCategory, AttachmentName, Attachmentbytes})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EmailUtilityServicesSPCTAsync(ByVal ProcessType As String, ByVal FromAddress As String, ByVal ToAddress As String, ByVal MailSubject As String, ByVal MailCC As String, ByVal MAILBCC As String, ByVal MailBody As String, ByVal MailCategory As String, ByVal AttachmentName() As String, ByVal Attachmentbytes()() As Byte)
            Me.EmailUtilityServicesSPCTAsync(ProcessType, FromAddress, ToAddress, MailSubject, MailCC, MAILBCC, MailBody, MailCategory, AttachmentName, Attachmentbytes, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EmailUtilityServicesSPCTAsync(ByVal ProcessType As String, ByVal FromAddress As String, ByVal ToAddress As String, ByVal MailSubject As String, ByVal MailCC As String, ByVal MAILBCC As String, ByVal MailBody As String, ByVal MailCategory As String, ByVal AttachmentName() As String, ByVal Attachmentbytes()() As Byte, ByVal userState As Object)
            If (Me.EmailUtilityServicesSPCTOperationCompleted Is Nothing) Then
                Me.EmailUtilityServicesSPCTOperationCompleted = AddressOf Me.OnEmailUtilityServicesSPCTOperationCompleted
            End If
            Me.InvokeAsync("EmailUtilityServicesSPCT", New Object() {ProcessType, FromAddress, ToAddress, MailSubject, MailCC, MAILBCC, MailBody, MailCategory, AttachmentName, Attachmentbytes}, Me.EmailUtilityServicesSPCTOperationCompleted, userState)
        End Sub
        
        Private Sub OnEmailUtilityServicesSPCTOperationCompleted(ByVal arg As Object)
            If (Not (Me.EmailUtilityServicesSPCTCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EmailUtilityServicesSPCTCompleted(Me, New EmailUtilityServicesSPCTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub EmailUtilityServicesCompletedEventHandler(ByVal sender As Object, ByVal e As EmailUtilityServicesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EmailUtilityServicesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub EmailUtilityServicesSPCTCompletedEventHandler(ByVal sender As Object, ByVal e As EmailUtilityServicesSPCTCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EmailUtilityServicesSPCTCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
